### ISSUE TITLE
Ampache Collection not displayed

### ISSUE THREAD

**Issue by thrillfall** [tomahawk-player/tomahawk-android#26]
I use the ownCloud (8.2.2) music app (lastest) with ampache support activated along with a tomahawk nightly build (0.951_armv7a). The connection is https with a letsencrypt certificate.
I can log in just fine and also it seems as if the query for the collection xml is returned from ampache.
In my owncloud logs i see two call which both return as 200. One for the action 'handshake' and another for action 'songs'. I replayed the later request in browser and it showed me an xml holding all the music information expected.
But in the app nothing shows. The circle right beside the ampache menu point does rotate forever. 

`adb logcat | grep ampache` shows the following:

```
D/ScriptInterface(19950): log: ampache: registerPlugin: resolver id: 0
D/ScriptInterface(19950): log: ampache: New auth token: odfjeg98vjremovedc865dd9
D/ScriptInterface(19950): log: ampache: Ampache Resolver properly initialised!
D/CollectionDb(19950): Constructed CollectionDb 'ampache_collection.db' with version 5, objectId: 504854388
D/ScriptResolver(19950): ScriptResolver ampache initialized successfully.
D/ScriptInterface(19950): log: ampache: Collection database has been changed. Wiping and re-fetching...
D/ScriptInterface(19950): log: ampache: Checking if collection needs to be updated
D/ScriptInterface(19950): log: ampache: registerPlugin: collection id: 1
D/ScriptInterface(19950): log: ampache: Collection needs to be updated
D/DbCollection(19950): ampache - Fuzzy index initialized. Resolving all waiting queries.
```

`logcat` without grep shows an exception. Though i do not know if this is related:

```
D/ScriptInterface(20689): log: ampache: Collection needs to be updated
W/System.err(20689): com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Invalid double: ""
W/System.err(20689):    at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:249)
W/System.err(20689):    at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:239)
W/System.err(20689):    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:117)
W/System.err(20689):    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:217)
W/System.err(20689):    at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
W/System.err(20689):    at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
W/System.err(20689):    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:117)
W/System.err(20689):    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:217)
W/System.err(20689):    at com.google.gson.Gson.fromJson(Gson.java:861)
W/System.err(20689):    at com.google.gson.Gson.fromJson(Gson.java:826)
W/System.err(20689):    at com.google.gson.Gson.fromJson(Gson.java:775)
W/System.err(20689):    at com.google.gson.Gson.fromJson(Gson.java:747)
W/System.err(20689):    at org.tomahawk.libtomahawk.resolver.ScriptInterface.invokeNativeScriptJob(ScriptInterface.java:284)
W/System.err(20689):    at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
W/System.err(20689):    at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:53)
W/System.err(20689):    at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err(20689):    at android.os.Looper.loop(Looper.java:135)
W/System.err(20689):    at android.os.HandlerThread.run(HandlerThread.java:61)
W/System.err(20689): Caused by: java.lang.NumberFormatException: Invalid double: ""
W/System.err(20689):    at java.lang.StringToReal.invalidReal(StringToReal.java:63)
W/System.err(20689):    at java.lang.StringToReal.parseDouble(StringToReal.java:267)
W/System.err(20689):    at java.lang.Double.parseDouble(Double.java:301)
W/System.err(20689):    at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1205)
W/System.err(20689):    at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:247)
W/System.err(20689):    ... 17 more
D/FuzzyIndex(20689): create - recreate:true
D/FuzzyIndex(20689): beginIndexing - recreate: true
D/FuzzyIndex(20689): endIndexing
D/TomahawkWebChromeClient(20689): Ampache - Uncaught error:{} -- From line 52 of file:///android_asset/js/tomahawk.js
D/FuzzyIndex(20689): Adding tracks to index - count: 0
D/FuzzyIndex(20689): endIndexing
D/FuzzyIndex(20689): updateSearcherManager
```

**Comment by thrillfall** [comment]
With owncloud updated to 9.0 the error message slightly changed. Now it shows `Invalid int: ""` instead of `invalid double`
```
D/ScriptInterface(25733): log: ampache: registerPlugin: collection id: 1
D/ScriptInterface(25733): log: ampache: Collection needs to be updated
W/System.err(25733): com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Invalid int: ""
W/System.err(25733):    at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:249)
W/System.err(25733):    at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:239)
W/System.err(25733):    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:117)
W/System.err(25733):    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:217)
W/System.err(25733):    at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
W/System.err(25733):    at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
W/System.err(25733):    at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
W/System.err(25733):    at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:52)
W/System.err(25733):    at com.google.gson.Gson.fromJson(Gson.java:861)
W/System.err(25733):    at com.google.gson.Gson.fromJson(Gson.java:926)
W/System.err(25733):    at org.tomahawk.libtomahawk.resolver.ScriptAccount.invokeNativeScriptJob(ScriptAccount.java:418)
W/System.err(25733):    at org.tomahawk.libtomahawk.resolver.ScriptInterface.invokeNativeScriptJob(ScriptInterface.java:164)
W/System.err(25733):    at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
W/System.err(25733):    at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:53)
W/System.err(25733):    at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err(25733):    at android.os.Looper.loop(Looper.java:135)
W/System.err(25733):    at android.os.HandlerThread.run(HandlerThread.java:61)
W/System.err(25733): Caused by: java.lang.NumberFormatException: Invalid int: ""
W/System.err(25733):    at java.lang.Integer.invalidInt(Integer.java:138)
W/System.err(25733):    at java.lang.Integer.parseInt(Integer.java:358)
W/System.err(25733):    at java.lang.Integer.parseInt(Integer.java:334)
W/System.err(25733):    at com.google.gson.JsonPrimitive.getAsInt(JsonPrimitive.java:260)
W/System.err(25733):    at com.google.gson.internal.bind.JsonTreeReader.nextInt(JsonTreeReader.java:197)
W/System.err(25733):    at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:247)
W/System.err(25733):    ... 16 more
D/FuzzyIndex(25733): FuzzyIndex constructor called: ampache
D/FuzzyIndex(25733): create - using CollectionDb 419457774 with id ampache
D/FuzzyIndex(25733): create - recreate:true
D/FuzzyIndex(25733): beginIndexing - recreate: true
D/FuzzyIndex(25733): endIndexing
D/FuzzyIndex(25733): Adding tracks to index - count: 0
D/FuzzyIndex(25733): endIndexing
D/FuzzyIndex(25733): updateSearcherManager
D/DbCollection(25733): ampache - Fuzzy index initialized. Resolving all waiting queries. 
```

**Comment by thrillfall** [comment]
With owncloud updated to 9.0 and `tomahawk-android-armv7a-20160328` the error message slightly changed. Now it shows `Invalid int: ""` instead of `invalid double`
```
D/ScriptInterface(25733): log: ampache: registerPlugin: collection id: 1
D/ScriptInterface(25733): log: ampache: Collection needs to be updated
W/System.err(25733): com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Invalid int: ""
W/System.err(25733):    at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:249)
W/System.err(25733):    at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:239)
W/System.err(25733):    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:117)
W/System.err(25733):    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:217)
W/System.err(25733):    at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
W/System.err(25733):    at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
W/System.err(25733):    at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
W/System.err(25733):    at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:52)
W/System.err(25733):    at com.google.gson.Gson.fromJson(Gson.java:861)
W/System.err(25733):    at com.google.gson.Gson.fromJson(Gson.java:926)
W/System.err(25733):    at org.tomahawk.libtomahawk.resolver.ScriptAccount.invokeNativeScriptJob(ScriptAccount.java:418)
W/System.err(25733):    at org.tomahawk.libtomahawk.resolver.ScriptInterface.invokeNativeScriptJob(ScriptInterface.java:164)
W/System.err(25733):    at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
W/System.err(25733):    at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:53)
W/System.err(25733):    at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err(25733):    at android.os.Looper.loop(Looper.java:135)
W/System.err(25733):    at android.os.HandlerThread.run(HandlerThread.java:61)
W/System.err(25733): Caused by: java.lang.NumberFormatException: Invalid int: ""
W/System.err(25733):    at java.lang.Integer.invalidInt(Integer.java:138)
W/System.err(25733):    at java.lang.Integer.parseInt(Integer.java:358)
W/System.err(25733):    at java.lang.Integer.parseInt(Integer.java:334)
W/System.err(25733):    at com.google.gson.JsonPrimitive.getAsInt(JsonPrimitive.java:260)
W/System.err(25733):    at com.google.gson.internal.bind.JsonTreeReader.nextInt(JsonTreeReader.java:197)
W/System.err(25733):    at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:247)
W/System.err(25733):    ... 16 more
D/FuzzyIndex(25733): FuzzyIndex constructor called: ampache
D/FuzzyIndex(25733): create - using CollectionDb 419457774 with id ampache
D/FuzzyIndex(25733): create - recreate:true
D/FuzzyIndex(25733): beginIndexing - recreate: true
D/FuzzyIndex(25733): endIndexing
D/FuzzyIndex(25733): Adding tracks to index - count: 0
D/FuzzyIndex(25733): endIndexing
D/FuzzyIndex(25733): updateSearcherManager
D/DbCollection(25733): ampache - Fuzzy index initialized. Resolving all waiting queries. 
```

**Comment by e-alfred** [comment]
I have the same problem. I am running Owncloud 8.2.3 with Music App 0.3.10. Running Tomahawk on desktop the Ampache collection is shown. Running the latest Tomahawk for Android Nightly it authenticates correctly but the collection is not shown.

**Comment by theli-ua** [comment]
Is there way you guys could provide somehow an access to your ampache (read-only user, is this a thing there?) so that this could be debugged?

**Comment by qirtaiba** [comment]
My ownCloud Ampache is not coming up in the Android app at all despite working in the desktop app. I have a valid Let's Encrypt cert. I am happy to open my system to someone to debug.

**Comment by thrillfall** [comment]
So it has been 5 years now and Nextcloud and ultrasonic app work fine
